Repository 2024-Fall-CapstoneDesign/newReals_FE, pull requests merged in 2024-11, with the labels that each got.

#10 [feat] : Footer 구현
  src/components/common/footer/Footer.tsx
  src/components/common/footer/FooterStyle.tsx
  src/index.css
  src/main.tsx
Labels: ✨ feature, 💄 ui

#13 [feat] : Header 구현
  .github/issue_template.md
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  build.sh
  public/images/Logo.svg
  src/AppRouter.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderStyle.tsx
  src/components/common/header/SearchBar.tsx
  src/components/common/header/SearchBarStyle.tsx
Labels: ✨ feature

#15 [refactor] : 1280 사이즈에 맞춰 다시 크기 조정
  public/icons/OIcon.svg
  public/icons/XIcon.svg
  src/components/common/bookmark/BookmarkStyle.tsx
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonStyle.tsx
  src/components/common/button/PageButtonStyle.tsx
  src/components/common/card/CardStyle.tsx
  src/components/common/chip/ChipStyle.tsx
  src/components/common/footer/FooterStyle.tsx
  src/components/common/quizAnswer/QuizAnswer.tsx
  src/components/common/quizAnswer/QuizAnswerStyle.tsx
  src/components/common/quizAnswer/chip/ChipStyle.tsx
  src/components/common/tag/TagStyle.tsx
  src/components/newsDetail/emojiCount/EmojiCountStyle.tsx
  src/components/newsDetail/quiz/QuizStyle.tsx
Labels: 🛠 refactor, 💄 ui

#18 [refactor] : 아이콘, 이미지 파일 위치 수정
  public/images/.keep
  src/assets/icons/AngryEmoji.svg
  src/assets/icons/BookmarkActiveIcon.svg
  src/assets/icons/BookmarkIcon.svg
  src/assets/icons/CheckActiveIcon.svg
  src/assets/icons/CheckIcon.svg
  src/assets/icons/CoinIcon.svg
  src/assets/icons/CongratulationEmoji.svg
  src/assets/icons/DownArrowIcon.svg
  src/assets/icons/EmojiesIcon.svg
  src/assets/icons/GoodEmoji.svg
  src/assets/icons/HeartEmoji.svg
  src/assets/icons/InfoIcon.svg
  src/assets/icons/InstagramIcon.svg
  src/assets/icons/LeftArrowIcon.svg
  src/assets/icons/MailIcon.svg
  src/assets/icons/MarketIcon.svg
  src/assets/icons/NotionIcon.svg
  src/assets/icons/OIcon.svg
  src/assets/icons/PauseIcon.svg
  src/assets/icons/PeopleIcon.svg
  src/assets/icons/RightArrowIcon.svg
  src/assets/icons/SadEmoji.svg
  src/assets/icons/SearchIcon.svg
  src/assets/icons/UpArrowIcon.svg
  src/assets/icons/XIcon.svg
  src/assets/images/Logo.svg
  src/components/common/bookmark/Bookmark.tsx
  src/components/common/button/PageButton.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/SearchBar.tsx
  src/components/common/quizAnswer/QuizAnswer.tsx
  src/components/newsDetail/emojiCount/EmojiCount.tsx
  src/components/newsDetail/quiz/Quiz.tsx
Labels: 🛠 refactor

#20 [feat] : register 페이지 구현
  index.html
  src/App.tsx
  src/AppRouter.tsx
  src/assets/icons/InfoIcon.svg
  src/components/common/header/Header.tsx
  src/components/common/header/HeaderStyle.tsx
  src/components/common/tabBar/TabBar.tsx
  src/components/common/tabBar/TabBarStyled.tsx
  src/components/register/errorMessage/ErrorMessage.tsx
  src/components/register/errorMessage/ErrorMessageSytle.tsx
  src/components/register/keyword/Keyword.tsx
  src/components/register/keyword/KeywordStyle.tsx
  src/components/register/keywordList/KeywordList.tsx
  src/components/register/keywordList/KeywordListStyle.tsx
  src/components/register/selectBox/SelectBox.tsx
  src/components/register/selectBox/SelectBoxStyle.tsx
  src/components/register/selectItem/SelectItem.tsx
  src/components/register/selectItem/SelectItemStyle.tsx
  src/components/register/subcategory/SubCategoryStyle.tsx
  src/components/register/subcategory/Subcategory.tsx
  src/components/register/text/Text.tsx
  src/components/register/text/TextStyle.tsx
  src/constants/Category.ts
  src/index.css
  src/main.tsx
  src/pages/register/Register.tsx
  src/pages/register/RegisterStyle.tsx
Labels: ✨ feature, 💄 ui

#26 [refactor] : JSDoc 및 스타일링 파일 확장자 변경
  src/components/common/bookmark/Bookmark.Style.ts
  src/components/common/bookmark/Bookmark.tsx
  src/components/common/button/Button.Style.ts
  src/components/common/button/Button.tsx
  src/components/common/button/ButtonStyle.tsx
  src/components/common/button/PageButton.Style.ts
  src/components/common/button/PageButton.tsx
  src/components/common/card/Card.Style.ts
  src/components/common/card/Card.tsx
  src/components/common/chip/Chip.Style.ts
  src/components/common/chip/Chip.tsx
  src/components/common/footer/Footer.Style.ts
  src/components/common/footer/Footer.tsx
  src/components/common/headNews/HeadNews.Style.ts
  src/components/common/headNews/HeadNews.tsx
  src/components/common/header/Header.Style.ts
  src/components/common/header/Header.tsx
  src/components/common/header/SearchBar.Style.ts
  src/components/common/header/SearchBar.tsx
  src/components/common/pageNation/PageNation.Style.ts
  src/components/common/pageNation/PageNation.tsx
  src/components/common/quizAnswer/QuizAnswer.Style.ts
  src/components/common/quizAnswer/QuizAnswer.tsx
  src/components/common/quizAnswer/chip/Chip.Style.ts
  src/components/common/quizAnswer/chip/Chip.tsx
  src/components/common/tabBar/TabBar.Style.ts
  src/components/common/tabBar/TabBar.tsx
  src/components/common/tag/Tag.Style.ts
  src/components/common/tag/Tag.tsx
  src/components/home/cartoon/Cartoon.Style.ts
  src/components/home/cartoon/Cartoon.tsx
  src/components/home/latestNews/LatestNews.Style.tsx
  src/components/home/latestNews/LatestNews.tsx
  src/components/newsDetail/.keep
  src/components/newsDetail/aiSummary/AISummary.Style.ts
  src/components/newsDetail/aiSummary/AISummary.tsx
  src/components/newsDetail/emojiCount/EmojiCount.Style.ts
  src/components/newsDetail/emojiCount/EmojiCount.tsx
  src/components/newsDetail/quiz/Quiz.Style.ts
  src/components/newsDetail/quiz/Quiz.tsx
  src/components/register/errorMessage/ErrorMessage.Sytle.ts
  src/components/register/errorMessage/ErrorMessage.tsx
  src/components/register/keyword/Keyword.Style.ts
  src/components/register/keyword/Keyword.tsx
  src/components/register/keywordList/KeywordList.Style.ts
  src/components/register/keywordList/KeywordList.tsx
  src/components/register/selectBox/SelectBox.Style.ts
  src/components/register/selectBox/SelectBox.tsx
  src/components/register/selectItem/SelectItem.Style.ts
  src/components/register/selectItem/SelectItem.tsx
  src/components/register/subcategory/SubCategory.Style.ts
  src/components/register/subcategory/Subcategory.tsx
  src/components/register/text/Text.Style.ts
  src/components/register/text/Text.tsx
  src/pages/home/Home.Style.ts
  src/pages/home/Home.tsx
  src/pages/register/Register.Style.ts
  src/pages/register/Register.tsx
Labels: 🛠 refactor

#28 #27 [feat] : 퀴즈 모달 구현
  index.html
  src/AppRouter.tsx
  src/components/common/modal/Modal.Style.ts
  src/components/common/modal/Modal.tsx
  src/components/common/modal/Portal.tsx
  src/components/newsDetail/quiz/AnswerModal.Style.ts
  src/components/newsDetail/quiz/AnswerModal.tsx
  src/components/newsDetail/quiz/PointAlert.Style.ts
  src/components/newsDetail/quiz/PointAlert.tsx
  src/components/newsDetail/quiz/Quiz.tsx
  src/index.css
  src/pages/newsDetail/NewsDetail.tsx
Labels: ✨ feature

#30 [feat] : 마켓 페이지 헤더 구현
  src/assets/icons/MarketIcon.svg
  src/components/common/chip/PointAlert.Style.ts
  src/components/common/chip/PointAlert.tsx
  src/components/common/header/Header.Style.ts
  src/components/common/header/Header.tsx
  src/components/newsDetail/quiz/AnswerModal.tsx
  src/components/newsDetail/quiz/PointAlert.Style.ts
  src/components/newsDetail/quiz/PointAlert.tsx
Labels: ✨ feature

#32 [feat] : 큰 카테고리 페이지 UI 구현 완료
  src/components/common/cardList/CardList.Style.ts
  src/components/common/cardList/CardList.tsx
  src/components/common/headNews/HeadNews.Style.ts
  src/components/common/headNews/HeadNews.tsx
  src/components/common/header/Header.Style.ts
  src/components/common/header/Header.tsx
  src/components/home/latestNews/LatestNews.tsx
  src/components/register/selectBox/SelectBox.Style.ts
  src/pages/category/Category.style.ts
  src/pages/category/Category.tsx
  src/pages/home/Home.Style.ts
Labels: ✨ feature, 💄 ui

#35 [refactor] : 글로벌 폰트, 컬러 수정
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/components/common/bookmark/Bookmark.Style.ts
  src/components/common/button/Button.Style.ts
  src/components/common/button/PageButton.Style.ts
  src/components/common/card/Card.Style.ts
  src/components/common/chip/Chip.Style.ts
  src/components/common/chip/PointAlert.Style.ts
  src/components/common/footer/Footer.Style.ts
  src/components/common/headNews/HeadNews.Style.ts
  src/components/common/header/Header.Style.ts
  src/components/common/header/SearchBar.Style.ts
  src/components/common/modal/Modal.Style.ts
  src/components/common/pageNation/PageNation.Style.ts
  src/components/common/quizAnswer/QuizAnswer.Style.ts
  src/components/common/quizAnswer/chip/Chip.Style.ts
  src/components/common/tabBar/TabBar.Style.ts
  src/components/common/tag/Tag.Style.ts
  src/components/home/cartoon/Cartoon.Style.ts
  src/components/home/latestNews/LatestNews.Style.tsx
  src/components/interest/.keep
  src/components/newsDetail/aiSummary/AISummary.Style.ts
  src/components/newsDetail/emojiCount/EmojiCount.Style.ts
  src/components/newsDetail/quiz/AnswerModal.Style.ts
  src/components/newsDetail/quiz/Quiz.Style.ts
  src/components/register/errorMessage/ErrorMessage.Sytle.ts
  src/components/register/keyword/Keyword.Style.ts
  src/components/register/selectBox/SelectBox.Style.ts
  src/components/register/selectItem/SelectItem.Style.ts
  src/components/register/subcategory/SubCategory.Style.ts
  src/components/register/text/Text.Style.ts
  src/index.css
  src/main.tsx
  src/pages/category/Category.Style.ts
  src/pages/category/Category.tsx
  src/reset.css
  src/styles/Colors.ts
  src/styles/FontStyles.ts
  src/styles/Fonts.ts
  src/styles/Globalstyles.Style.ts
  src/styles/index.ts
Labels: 🛠 refactor

#36 #35 [fix] : 폰트 파일 위치 수정
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
Labels: 🔨 fix

#34 [feat] : 기사 헤더 구현
  src/components/common/bookmark/Bookmark.Style.ts
  src/components/common/bookmark/Bookmark.tsx
  src/components/newsDetail/articleHeader/ArticleHeader.Style.ts
  src/components/newsDetail/articleHeader/ArticleHeader.tsx
  src/pages/newsDetail/NewsDetail.tsx
Labels: ✨ feature

#39 [feat] : 프로필 페이지 UI 구현
  package-lock.json
  package.json
  src/assets/icons/CalendarCoinIcon.svg
  src/assets/icons/CalendarNoCoinIcon.svg
  src/assets/icons/DotIcon.svg
  src/assets/icons/EditIcon.svg
  src/assets/icons/OStampIcon.svg
  src/assets/icons/XStampIcon.svg
  src/components/common/cardList/CardList.Style.ts
  src/components/common/chip/Chip.Style.ts
  src/components/common/chip/Chip.tsx
  src/components/common/headNews/HeadNews.Style.ts
  src/components/common/header/Header.Style.ts
  src/components/common/header/Header.tsx
  src/components/common/header/SearchBar.tsx
  src/components/home/cartoon/Cartoon.Style.ts
  src/components/home/latestNews/LatestNews.Style.tsx
  src/components/profile/.keep
  src/components/profile/analysisCard/AnalysisCard.Style.ts
  src/components/profile/analysisCard/AnalysisCard.tsx
  src/components/profile/analysisCard/chart/Chart.Style.ts
  src/components/profile/analysisCard/chart/Chart.tsx
  src/components/profile/analysisCard/grade/Grade.Style.ts
  src/components/profile/analysisCard/grade/Grade.tsx
  src/components/profile/calendar/Calendar.Style.ts
  src/components/profile/calendar/Calendar.tsx
  src/components/profile/profileCard/ProfileCard.Style.ts
  src/components/profile/profileCard/ProfileCard.tsx
  src/components/profile/profileCard/coinExplain/CoinExplain.Style.ts
  src/components/profile/profileCard/coinExplain/CoinExplain.tsx
  src/components/profile/profileImage/ProfileImage.Style.ts
  src/components/profile/profileImage/ProfileImage.tsx
  src/components/profile/quiz/Quiz.Style.ts
  src/components/profile/quiz/Quiz.tsx
  src/components/profile/scrap/Scrap.Style.ts
  src/components/profile/scrap/Scrap.tsx
  src/pages/home/Home.Style.ts
  src/pages/profile/Profile.Style.ts
  src/pages/profile/Profile.tsx
  src/styles/FontStyles.ts
Labels: ✨ feature, 💄 ui

#43 [feat] : 기사 페이지 이모지파트
  src/components/newsDetail/emojipart/EmojiPart.Style.ts
  src/components/newsDetail/emojipart/EmojiPart.tsx
  src/components/newsDetail/emojipart/IconPart.Style.ts
  src/components/newsDetail/emojipart/IconPart.tsx
  src/pages/newsDetail/NewsDetail.tsx
Labels: ✨ feature

#41 [feat] : 프로필 편집 모달 UI 구현
  src/assets/images/DefaultProfileImg.png
  src/components/common/button/Button.Style.ts
  src/components/common/button/Button.tsx
  src/components/profile/modal/EditProfile.Style.ts
  src/components/profile/modal/EditProfile.tsx
  src/components/profile/profileImage/ProfileImage.tsx
  src/pages/profile/Profile.tsx
Labels: 💄 ui

#44 [feat] : 관심 키워드 수정 모달 UI 구현 완료
  src/components/common/keyword/Keyword.Style.ts
  src/components/common/keyword/Keyword.tsx
  src/components/common/keywordList/KeywordList.Style.ts
  src/components/common/keywordList/KeywordList.tsx
  src/components/common/subcategory/SubCategory.Style.ts
  src/components/common/subcategory/Subcategory.tsx
  src/components/profile/editProfile/EditProfile.Style.ts
  src/components/profile/editProfile/EditProfile.tsx
  src/components/profile/keywordModal/KeywordModal.Style.ts
  src/components/profile/keywordModal/KeywordModal.tsx
  src/components/profile/keywordModal/TabBar.Style.ts
  src/components/profile/keywordModal/TabBar.tsx
  src/components/register/keywordList/KeywordList.Style.ts
  src/components/register/subcategory/SubCategory.Style.ts
  src/pages/profile/Profile.tsx
  src/pages/register/Register.tsx
Labels: ✨ feature, 💄 ui

#46 [feat] : 코인 획득 모달 UI 구현
  src/assets/icons/ModalAction.svg
  src/components/common/coinModal/CoinModal.Style.ts
  src/components/common/coinModal/CoinModal.tsx
Labels: ✨ feature, 💄 ui

#48 [refactor] : 큰 카테고리 페이지 리팩토링
  src/components/category/.keep
  src/pages/category/Category.tsx
Labels: 🔨 fix, 🛠 refactor

#51 [feat] : 말풍선 호버 구현
  src/assets/icons/ErrorIcon.svg
  src/assets/icons/InfoIcon.svg
  src/components/profile/profileCard/ProfileCard.Style.ts
  src/components/profile/profileCard/ProfileCard.tsx
  src/components/profile/profileCard/coinExplain/CoinExplain.Style.ts
  src/components/register/errorMessage/ErrorMessage.tsx
Labels: ✨ feature

#52 [refactor] : 폴더 구조 정리
  src/components/register/selectBox/SelectBox.tsx
  src/components/register/selectBox/errorMessage/ErrorMessage.Sytle.ts
  src/components/register/selectBox/errorMessage/ErrorMessage.tsx
  src/components/register/selectBox/selectItem/SelectItem.Style.ts
  src/components/register/selectBox/selectItem/SelectItem.tsx
Labels: 🛠 refactor

#54 [refactor] : 글씨 추가
  src/components/profile/calendar/Calendar.tsx
Labels: 🛠 refactor

#56 [feat] : 뉴스상세페이지 쉬운해설 파트
  package-lock.json
  package.json
  src/components/newsDetail/aiSummary/AISummary.Style.ts
  src/components/newsDetail/aiSummary/AISummary.tsx
  src/components/newsDetail/easySummary/EasySummary.Style.ts
  src/components/newsDetail/easySummary/EasySummary.tsx
  src/components/newsDetail/easySummary/InfoPart.Style.ts
  src/components/newsDetail/easySummary/InfoPart.tsx
  src/pages/newsDetail/NewsDetail.tsx
  src/styles/Globalstyles.Style.ts
Labels: ✨ feature

#58 [feat] : 뉴스 상세페이지 UI 구현 완료
  src/components/intro/intro_2/Intro_2.Style.ts
  src/components/intro/intro_2/Intro_2.tsx
  src/components/newsDetail/aiPart/AIPart.Style.ts
  src/components/newsDetail/aiPart/AIPart.tsx
  src/components/newsDetail/aiPart/aiSummary/AISummary.Style.ts
  src/components/newsDetail/aiPart/aiSummary/AISummary.tsx
  src/components/newsDetail/aiPart/easySummary/EasySummary.Style.ts
  src/components/newsDetail/aiPart/easySummary/EasySummary.tsx
  src/components/newsDetail/aiPart/easySummary/InfoPart.Style.ts
  src/components/newsDetail/aiPart/easySummary/InfoPart.tsx
  src/components/newsDetail/articleHeader/ArticleHeader.tsx
  src/components/newsDetail/emojipart/EmojiPart.Style.ts
  src/components/newsDetail/quiz/Quiz.Style.ts
  src/pages/newsDetail/NewsDetail.Style.ts
  src/pages/newsDetail/NewsDetail.tsx
Labels: ✨ feature

#60 [refactor] : 버튼 크기 및 뉴스 상세 이동 수정
  src/components/common/button/Button.Style.ts
  src/components/common/cardList/CardList.tsx
Labels: 🛠 refactor, 💄 ui

#63 [feat] : 생각정리, 퀴즈 남은 시간 계산 구현 (뉴스 상세 페이지)
  .env
  src/components/common/tag/Tag.Style.ts
  src/components/common/tag/Tag.tsx
  src/components/newsDetail/quiz/Quiz.Style.ts
  src/components/newsDetail/quiz/Quiz.tsx
  src/components/newsDetail/thinkingPart/AfterThinking.Style.ts
  src/components/newsDetail/thinkingPart/AfterThinking.tsx
  src/components/newsDetail/thinkingPart/ThinkingPart.Style.ts
  src/components/newsDetail/thinkingPart/ThinkingPart.tsx
  src/pages/newsDetail/NewsDetail.tsx
  카카오로그인 앱 키.txt
Labels: ✨ feature

#69 [refactor] : 공통 버튼 스타일 수정
  src/components/common/button/Button.Style.ts
  src/components/common/button/Button.tsx
  src/components/newsDetail/quiz/Quiz.Style.ts
  src/components/newsDetail/quiz/Quiz.tsx
Labels: 🛠 refactor, 💄 ui

#71 [feat] : 홈페이지 인사이트 UI 구현
  src/components/home/cartoon/Cartoon.Style.ts
  src/components/home/cartoon/Cartoon.tsx
  src/components/home/insight/Insight.Style.ts
  src/components/home/insight/Insight.tsx
  src/components/home/insight/Item.Style.ts
  src/components/home/insight/Item.tsx
  src/pages/home/Home.tsx
Labels: ✨ feature, 💄 ui

#67 [feat] : 카카오로그인(백연동X)
  .gitignore
  src/AppRouter.tsx
  src/assets/icons/kakaoButton.svg
  src/components/common/Loading/Loading.Style.ts
  src/components/common/Loading/Loding.tsx
  src/components/intro/IntroContent.Style.ts
  src/components/intro/IntroContent.tsx
  src/components/intro/intro_1/Intro_1.Style.ts
  src/components/intro/intro_1/Intro_1.tsx
  src/components/intro/intro_2/Intro_2.Style.ts
  src/components/intro/intro_2/Intro_2.tsx
  src/components/intro/intro_3/Intro_3.Style.ts
  src/components/intro/intro_3/Intro_3.tsx
  src/components/intro/intro_4/Intro_4.Style.ts
  src/components/intro/intro_4/Intro_4.tsx
  src/components/intro/intro_5/Intro_5.Style.ts
  src/components/intro/intro_5/Intro_5.tsx
  src/components/intro/intro_6/Intro_6.Style.ts
  src/components/intro/intro_6/Intro_6.tsx
  src/components/intro/intro_7/Intro_7.Style.ts
  src/components/intro/intro_7/Intro_7.tsx
  src/components/intro/kakaoLogin/KakaoLogin.Style.ts
  src/components/intro/kakaoLogin/KakaoLogin.tsx
  src/components/intro/kakaoLogin/RedirectPage.tsx
  src/pages/intro/Intro.tsx
Labels: ✨ feature

#73 [feat] : 마이 레포트 UI 구현(그래프 제외)
  src/components/common/headNews/HeadNews.Style.ts
  src/components/home/insight/Insight.tsx
  src/components/home/insight/Item.tsx
  src/components/profile/activities/Activites.Style.ts
  src/components/profile/activities/Activities.tsx
  src/components/profile/activities/analysisCard/AnalysisCard.Style.ts
  src/components/profile/activities/analysisCard/AnalysisCard.tsx
  src/components/profile/activities/analysisCard/chart/Chart.Style.ts
  src/components/profile/activities/analysisCard/chart/Chart.tsx
  src/components/profile/activities/analysisCard/grade/Grade.Style.ts
  src/components/profile/activities/analysisCard/grade/Grade.tsx
  src/components/profile/activities/insight/Insight.Style.ts
  src/components/profile/activities/insight/Insight.tsx
  src/components/profile/activities/insight/Item.Style.ts
  src/components/profile/activities/insight/Item.tsx
  src/components/profile/activities/quiz/Quiz.Style.ts
  src/components/profile/activities/quiz/Quiz.tsx
  src/components/profile/activities/scrap/Scrap.Style.ts
  src/components/profile/activities/scrap/Scrap.tsx
  src/components/profile/report/Report.Style.ts
  src/components/profile/report/Report.tsx
  src/components/profile/report/graph/Graph.Style.ts
  src/components/profile/report/graph/Graph.tsx
  src/components/profile/report/interest/Bubble.tsx
  src/components/profile/report/interest/Bublble.Style.tsx
  src/components/profile/report/interest/Count.Style.ts
  src/components/profile/report/interest/Count.tsx
  src/components/profile/report/interest/Interest.Style.ts
  src/components/profile/report/interest/Interest.tsx
  src/components/profile/report/keyword/Kewyord.Style.tsx
  src/components/profile/report/keyword/Keyword.tsx
  src/components/profile/report/keyword/KeywordList.Style.ts
  src/components/profile/report/keyword/KeywordList.tsx
  src/components/profile/report/summary/Summary.Style.ts
  src/components/profile/report/summary/Summary.tsx
  src/components/profile/report/trend/Item.Style.ts
  src/components/profile/report/trend/Item.tsx
  src/components/profile/report/trend/Trend.Style.ts
  src/components/profile/report/trend/Trend.tsx
  src/pages/profile/Profile.Style.ts
  src/pages/profile/Profile.tsx
Labels: ✨ feature, 💄 ui

#75 [feat] : 소셜 로그인 API 연동 및 관심사 페이지 관심 키워드 선택 API 연동
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/AppRouter.tsx
  src/api/Interest.ts
  src/api/Login.ts
  src/api/instance.ts
  src/components/intro/kakaoLogin/RedirectPage.tsx
  src/components/register/selectBox/SelectBox.tsx
  src/main.tsx
  src/pages/register/Register.tsx
Labels: ⚙ api, ✨ feature

#78 [feat] : 프로필 페이지 일부 API 연동
  src/api/Profile.ts
  src/components/profile/activities/insight/Insight.tsx
  src/components/profile/calendar/Calendar.tsx
  src/components/profile/editProfile/EditProfile.tsx
  src/components/profile/profileCard/ProfileCard.tsx
  src/pages/profile/Profile.tsx
Labels: ⚙ api, ✨ feature

#82 [fix] : 백엔드 로그인 구현 방식 변경으로 인한 수정 작업
  src/App.tsx
  src/Router.tsx
  src/api/Interest.ts
  src/components/intro/kakaoLogin/RedirectPage.tsx
  src/components/register/selectBox/SelectBox.tsx
Labels: ⚙ api, ✨ feature, 🔨 fix

#83 [refactor] : 인트로 페이지
  public/fonts/Syncopate-Bold.woff2
  src/assets/icons/IntroLoginIcon.svg
  src/assets/icons/Logo.svg
  src/assets/images/IntroImg1.png
  src/assets/images/IntroImg3.png
  src/assets/images/IntroImg4.png
  src/assets/images/IntroImg4_2.png
  src/assets/images/IntroImg5.png
  src/assets/images/IntroImg6.png
  src/assets/images/IntroImg7.png
  src/components/common/header/Header.tsx
  src/components/intro/commonLayout/CommonLayout.Style.ts
  src/components/intro/commonLayout/CommonLayout.tsx
  src/components/intro/commonLayout/IntroContent.Style.ts
  src/components/intro/commonLayout/IntroContent.tsx
  src/components/intro/intro_1/Intro_1.Style.ts
  src/components/intro/intro_1/Intro_1.tsx
  src/components/intro/intro_2/Intro_2.Style.ts
  src/components/intro/intro_2/Intro_2.tsx
  src/components/intro/intro_3/Intro_3.Style.ts
  src/components/intro/intro_3/Intro_3.tsx
  src/components/intro/intro_4/Intro_4.Style.ts
  src/components/intro/intro_4/Intro_4.tsx
  src/components/intro/intro_5/Intro_5.Style.ts
  src/components/intro/intro_5/Intro_5.tsx
  src/components/intro/intro_6/Intro_6.Style.ts
  src/components/intro/intro_6/Intro_6.tsx
  src/components/intro/intro_7/Intro_7.Style.ts
  src/components/intro/intro_7/Intro_7.tsx
  src/components/intro/kakaoLogin/KakaoLogin.Style.ts
  src/components/intro/kakaoLogin/KakaoLogin.tsx
  src/pages/intro/Intro.Style.ts
  src/pages/intro/Intro.tsx
  src/styles/Fonts.ts
  src/styles/Globalstyles.Style.ts
Labels: ✨ feature, 🛠 refactor

#86 [refactor] : 인트로 페이지 구현 완료
  public/fonts/Syncopate-Bold.woff2
  src/assets/icons/IntroLoginIcon.svg
  src/assets/icons/Logo.svg
  src/assets/images/IntroImg1.png
  src/assets/images/IntroImg3.png
  src/assets/images/IntroImg4.png
  src/assets/images/IntroImg4_2.png
  src/assets/images/IntroImg5.png
  src/assets/images/IntroImg6.png
  src/assets/images/IntroImg7.png
  src/components/common/header/Header.tsx
  src/components/intro/commonLayout/CommonLayout.Style.ts
  src/components/intro/commonLayout/CommonLayout.tsx
  src/components/intro/commonLayout/IntroContent.Style.ts
  src/components/intro/commonLayout/IntroContent.tsx
  src/components/intro/intro_1/Intro_1.Style.ts
  src/components/intro/intro_1/Intro_1.tsx
  src/components/intro/intro_2/Intro_2.Style.ts
  src/components/intro/intro_2/Intro_2.tsx
  src/components/intro/intro_3/Intro_3.Style.ts
  src/components/intro/intro_3/Intro_3.tsx
  src/components/intro/intro_4/Intro_4.Style.ts
  src/components/intro/intro_4/Intro_4.tsx
  src/components/intro/intro_5/Intro_5.Style.ts
  src/components/intro/intro_5/Intro_5.tsx
  src/components/intro/intro_6/Intro_6.Style.ts
  src/components/intro/intro_6/Intro_6.tsx
  src/components/intro/intro_7/Intro_7.Style.ts
  src/components/intro/intro_7/Intro_7.tsx
  src/components/intro/kakaoLogin/KakaoLogin.Style.ts
  src/components/intro/kakaoLogin/KakaoLogin.tsx
  src/pages/intro/Intro.Style.ts
  src/pages/intro/Intro.tsx
  src/styles/Fonts.ts
  src/styles/Globalstyles.Style.ts
Labels: ✨ feature, 🛠 refactor

#88 [feat] : 홈페이지 API 연동
  src/App.tsx
  src/api/Main.ts
  src/components/common/cardList/CardList.tsx
  src/components/common/headNews/HeadNews.Style.ts
  src/components/common/headNews/HeadNews.tsx
  src/components/common/pageNation/PageNation.tsx
  src/components/home/insight/Insight.tsx
  src/components/home/latestNews/LatestNews.tsx
  src/components/intro/intro_1/Intro_1.Style.ts
  src/components/intro/intro_2/Intro_2.Style.ts
  src/pages/home/Home.tsx
  src/styles/Globalstyles.Style.ts
  카카오로그인 앱 키.txt
Labels: ⚙ api, ✨ feature

#90 [feat] : 큰 카테고리 페이지 API 연동
  src/api/Category.ts
  src/components/common/cardList/CardList.tsx
  src/components/common/tabBar/TabBar.tsx
  src/components/home/latestNews/LatestNews.tsx
  src/pages/category/Category.tsx
  src/pages/register/Register.tsx
Labels: ⚙ api, ✨ feature

#92 [feat] : 마이페이지 일부 API 연동 완료
  src/api/Profile.ts
  src/components/common/keyword/Keyword.tsx
  src/components/common/keywordList/KeywordList.tsx
  src/components/home/insight/Item.Style.ts
  src/components/profile/activities/Activities.tsx
  src/components/profile/activities/scrap/Scrap.Style.ts
  src/components/profile/activities/scrap/Scrap.tsx
  src/components/profile/editProfile/EditProfile.tsx
  src/components/profile/keywordModal/KeywordModal.tsx
  src/pages/profile/Profile.tsx
Labels: ⚙ api, ✨ feature

#93 [api] : 뉴스 상세페이지 api 일부 연동 (공감클릭, 스크랩클릭, 용어 제외)
  src/components/home/insight/Item.tsx
  src/components/newsDetail/aiPart/AIPart.tsx
  src/components/newsDetail/aiPart/easySummary/EasySummary.tsx
  src/components/newsDetail/articleHeader/ArticleHeader.tsx
  src/components/newsDetail/emojipart/EmojiPart.tsx
  src/components/newsDetail/quiz/AnswerModal.tsx
  src/components/newsDetail/quiz/Quiz.tsx
  src/components/newsDetail/thinkingPart/AfterThinking.tsx
  src/components/newsDetail/thinkingPart/ThinkingPart.tsx
  src/pages/newsDetail/NewsDetail.tsx
Labels: ⚙ api, ✨ feature

#94 [feat] : 마이페이지 일부 API 연동
  src/api/Profile.ts
  src/components/common/headNews/HeadNews.tsx
  src/components/newsDetail/quiz/AnswerModal.tsx
  src/components/profile/activities/analysisCard/AnalysisCard.tsx
  src/components/profile/activities/quiz/Quiz.tsx
  src/constants/Category.ts
  src/pages/category/Category.tsx
Labels: ⚙ api, ✨ feature
