Repository 2024-Fall-CapstoneDesign/newReals_FE, pull requests merged in 2024-12, with the labels that each got.

#95 [feat] : 뉴스상세페이지 api 일부 연동 및 api 파일 분리
  src/api/NewsDetail.ts
  src/components/newsDetail/articleHeader/ArticleHeader.tsx
  src/components/newsDetail/quiz/Quiz.tsx
  src/components/newsDetail/thinkingPart/ThinkingPart.tsx
  src/pages/newsDetail/NewsDetail.tsx
Labels: ⚙ api, ✨ feature, 🛠 refactor

#96 [feat] : 마이페이지 분석 레포트 UI 및 API 연동 완료
  src/api/Profile.ts
  src/components/profile/activities/insight/Insight.tsx
  src/components/profile/activities/insight/Item.Style.ts
  src/components/profile/activities/insight/Item.tsx
  src/components/profile/report/Report.tsx
  src/components/profile/report/graph/Chip.Style.ts
  src/components/profile/report/graph/Chip.tsx
  src/components/profile/report/graph/Graph.Style.ts
  src/components/profile/report/graph/Graph.tsx
  src/components/profile/report/interest/Interest.tsx
  src/components/profile/report/keyword/Keyword.tsx
  src/components/profile/report/keyword/KeywordList.tsx
  src/components/profile/report/summary/Summary.tsx
  src/components/profile/report/trend/Item.tsx
  src/components/profile/report/trend/Trend.tsx
  src/components/profile/report/type/Report.ts
Labels: ⚙ api, ✨ feature, 💄 ui

#97 [feat] : 검색 기능 구현
  src/App.Style.ts
  src/App.tsx
  src/Router.tsx
  src/api/Search.ts
  src/components/common/header/Header.tsx
  src/components/common/header/SearchBar.tsx
  src/components/newsDetail/aiPart/easySummary/EasySummary.tsx
  src/pages/search/Search.Style.ts
  src/pages/search/Search.tsx
Labels: ⚙ api, ✨ feature

#98 [feat] : 뉴스상세페이지 공감버튼클릭 api 연동
  src/api/NewsDetail.ts
  src/components/newsDetail/aiPart/easySummary/EasySummary.tsx
  src/components/newsDetail/aiPart/easySummary/InfoPart.Style.ts
  src/components/newsDetail/emojipart/EmojiPart.tsx
  src/components/newsDetail/thinkingPart/ThinkingPart.tsx
  src/pages/newsDetail/NewsDetail.tsx
Labels: ⚙ api, ✨ feature

#101 [feat] : 출석 체크 연동
  src/api/Main.ts
  src/assets/icons/IntroLoginIcon.svg
  src/assets/icons/Logo.svg
  src/assets/images/IntroImg1.png
  src/assets/images/IntroImg3.png
  src/assets/images/IntroImg4.png
  src/assets/images/IntroImg5.png
  src/assets/images/IntroImg6.png
  src/assets/images/IntroImg7.png
  src/components/common/coinModal/CoinModal.Style.ts
  src/components/common/coinModal/CoinModal.tsx
  src/components/common/header/Header.tsx
  src/components/intro/intro1/Intro_1.Style.ts
  src/components/intro/intro1/Intro_1.tsx
  src/components/intro/intro2/Intro_2.Style.ts
  src/components/intro/intro2/Intro_2.tsx
  src/components/intro/intro_3/Intro_3.Style.ts
  src/components/intro/intro_3/Intro_3.tsx
  src/components/intro/intro_4/Intro_4.Style.ts
  src/components/intro/intro_4/Intro_4.tsx
  src/components/intro/intro_5/Intro_5.Style.ts
  src/components/intro/intro_5/Intro_5.tsx
  src/components/intro/intro_6/Intro_6.Style.ts
  src/components/intro/intro_6/Intro_6.tsx
  src/components/intro/intro_7/Intro_7.Style.ts
  src/components/intro/intro_7/Intro_7.tsx
  src/components/intro/kakaoLogin/KakaoLogin.Style.ts
  src/components/intro/kakaoLogin/KakaoLogin.tsx
  src/components/intro/layout/CommonLayout.Style.ts
  src/components/intro/layout/CommonLayout.tsx
  src/components/intro/layout/IntroContent.Style.ts
  src/components/intro/layout/IntroContent.tsx
  src/pages/home/Home.tsx
  src/pages/intro/Intro.Style.ts
  src/pages/intro/Intro.tsx
Labels: ⚙ api, 🐞 bug, ✨ feature, 🔨 fix

#103 [feat] : 뉴스 상세 페이지에서 스크랩 버튼 동작 API
  src/components/newsDetail/articleHeader/ArticleHeader.tsx
Labels: ⚙ api, ✨ feature

#104 [feat] : API 연동 완료 후 배포
  public/fonts/Syncopate-Bold.woff2
  src/api/Main.ts
  src/assets/icons/IntroLoginIcon.svg
  src/assets/icons/Logo.svg
  src/assets/images/IntroImg1.png
  src/assets/images/IntroImg3.png
  src/assets/images/IntroImg4.png
  src/assets/images/IntroImg5.png
  src/assets/images/IntroImg6.png
  src/assets/images/IntroImg7.png
  src/components/common/coinModal/CoinModal.Style.ts
  src/components/common/coinModal/CoinModal.tsx
  src/components/common/header/Header.tsx
  src/components/intro/intro1/Intro_1.Style.ts
  src/components/intro/intro1/Intro_1.tsx
  src/components/intro/intro2/Intro_2.Style.ts
  src/components/intro/intro2/Intro_2.tsx
  src/components/intro/intro_1/Intro_1.tsx
  src/components/intro/intro_3/Intro_3.Style.ts
  src/components/intro/intro_3/Intro_3.tsx
  src/components/intro/intro_4/Intro_4.Style.ts
  src/components/intro/intro_4/Intro_4.tsx
  src/components/intro/intro_5/Intro_5.Style.ts
  src/components/intro/intro_5/Intro_5.tsx
  src/components/intro/intro_6/Intro_6.Style.ts
  src/components/intro/intro_6/Intro_6.tsx
  src/components/intro/intro_7/Intro_7.Style.ts
  src/components/intro/intro_7/Intro_7.tsx
  src/components/intro/kakaoLogin/KakaoLogin.Style.ts
  src/components/intro/kakaoLogin/KakaoLogin.tsx
  src/components/intro/layout/CommonLayout.Style.ts
  src/components/intro/layout/CommonLayout.tsx
  src/components/intro/layout/IntroContent.Style.ts
  src/components/intro/layout/IntroContent.tsx
  src/components/newsDetail/articleHeader/ArticleHeader.tsx
  src/pages/home/Home.tsx
  src/pages/intro/Intro.Style.ts
  src/pages/intro/Intro.tsx
  src/styles/Fonts.ts
Labels: ⚙ api, ✨ feature, 💄 ui

#105 [feat] : 헤더 로그인 연결
  src/components/common/header/Header.tsx
Labels: ✨ feature, 🛠 refactor

#107 [fix] : vercel 배포
  vercel.json
Labels: ⚙ api, 🔨 fix

#108 [fix] : 버셀 배포 수정
  vercel.json
Labels: 🔨 fix

#109 [fix] : vercel 리다이렉트 수정
  vercel.json
Labels: 🔨 fix

#111 [fix] : 배포 환경에서 출석 아이콘 안보이는 현상 해결
  src/components/profile/calendar/Calendar.Style.ts
Labels: 🔨 fix

#113 [fix] : 배포 환경에서 출석 아이콘 안보이는 현상 해결
  src/components/profile/calendar/Calendar.Style.ts
Labels: 🔨 fix

#114 #110 [fix] : 배포 환경에서 출석 아이콘 안보이는 현상 해결
  public/assets/icons/CalendarCoinIcon.svg
  public/assets/icons/CalendarNoCoinIcon.svg
  src/components/profile/calendar/Calendar.Style.ts
Labels: 🔨 fix

#117 [fix] : QA 수정 요구 사항 반영 후 배포
  src/components/common/button/PageButton.Style.ts
  src/pages/newsDetail/NewsDetail.tsx
Labels: 🔨 fix

#119 [fix] : QA 수정 요구 사항 반영
  index.html
  src/components/common/card/Card.Style.ts
  src/components/common/chip/Chip.Style.ts
  src/components/common/pageNation/PageNation.Style.ts
  src/components/common/pageNation/PageNation.tsx
  src/components/home/insight/Item.Style.ts
  src/components/profile/activities/quiz/Quiz.Style.ts
  src/pages/category/Category.tsx
Labels: 🔨 fix

#118 [fix] : 양옆버튼 수정
  src/components/common/button/PageButton.Style.ts
  src/components/common/button/PageButton.tsx
Labels: 🔨 fix

#120 [fix] : QA 수정 요구 사항 반영
  index.html
  src/components/common/button/PageButton.Style.ts
  src/components/common/button/PageButton.tsx
  src/components/common/card/Card.Style.ts
  src/components/common/chip/Chip.Style.ts
  src/components/common/pageNation/PageNation.Style.ts
  src/components/common/pageNation/PageNation.tsx
  src/components/home/insight/Item.Style.ts
  src/components/profile/activities/quiz/Quiz.Style.ts
  src/pages/category/Category.tsx
Labels: 🔨 fix

#121 [fix] : QA 수정 요구 사항 반영
  src/components/profile/activities/scrap/Scrap.tsx
Labels: 🔨 fix

#126 [feat] : 레포트 없을 때 UI 구현
  src/assets/icons/NoreportIcon.svg
  src/components/profile/report/Report.Style.ts
  src/components/profile/report/Report.tsx
  src/components/profile/report/keyword/KeywordList.tsx
  src/pages/profile/Profile.tsx
Labels: ✨ feature, 💄 ui

#127 [refactor] : QA 수정 요구 사항 일부 반영
  src/api/Search.ts
  src/components/home/insight/Item.tsx
  src/components/home/latestNews/LatestNews.tsx
  src/components/profile/keywordModal/KeywordModal.Style.ts
  src/components/profile/keywordModal/KeywordModal.tsx
  src/pages/category/Category.Style.ts
  src/pages/home/Home.Style.ts
  src/pages/search/Search.Style.ts
  src/pages/search/Search.tsx
Labels: 🔨 fix, 🛠 refactor

#129 [fix] : 마이페이지 QA 수정 사항 반영
  src/api/Login.ts
  src/api/instance.ts
  src/components/intro/kakaoLogin/RedirectPage.tsx
  src/components/profile/activities/insight/Insight.tsx
Labels: 🔨 fix

#132 [feat] : 마켓페이지 UI 구현
  src/assets/images/MarketImg1.png
  src/assets/images/MarketImg2.png
  src/assets/images/MarketImg3.png
  src/components/market/.keep
  src/components/market/Item.Style.ts
  src/components/market/Item.tsx
  src/components/market/ItemList.Style.ts
  src/components/market/ItemList.tsx
  src/pages/market/Market.Style.ts
  src/pages/market/Market.tsx
Labels: 💄 ui

#130 [fix] : QA 수정 요구 사항 반영 및 UI 작업
  src/api/Login.ts
  src/api/Search.ts
  src/api/instance.ts
  src/assets/icons/NoInsightIcon.svg
  src/assets/icons/NoreportIcon.svg
  src/assets/images/MarketImg1.png
  src/assets/images/MarketImg2.png
  src/assets/images/MarketImg3.png
  src/components/home/insight/Item.tsx
  src/components/home/latestNews/LatestNews.tsx
  src/components/intro/kakaoLogin/RedirectPage.tsx
  src/components/market/.keep
  src/components/market/Item.Style.ts
  src/components/market/Item.tsx
  src/components/market/ItemList.Style.ts
  src/components/market/ItemList.tsx
  src/components/profile/activities/analysisCard/AnalysisCard.Style.ts
  src/components/profile/activities/analysisCard/AnalysisCard.tsx
  src/components/profile/activities/insight/Insight.Style.ts
  src/components/profile/activities/insight/Insight.tsx
  src/components/profile/activities/scrap/Scrap.Style.ts
  src/components/profile/activities/scrap/Scrap.tsx
  src/components/profile/keywordModal/KeywordModal.Style.ts
  src/components/profile/keywordModal/KeywordModal.tsx
  src/components/profile/report/Report.Style.ts
  src/components/profile/report/Report.tsx
  src/components/profile/report/keyword/KeywordList.tsx
  src/pages/category/Category.Style.ts
  src/pages/home/Home.Style.ts
  src/pages/market/Market.Style.ts
  src/pages/market/Market.tsx
  src/pages/profile/Profile.tsx
  src/pages/search/Search.Style.ts
  src/pages/search/Search.tsx
Labels: 🔨 fix, 💄 ui

#134 [feat] : 파비콘 설정 및 메타 태그 설정
  index.html
  public/assets/images/favicon.png
Labels: 📄 docs

#135 [refactor] : 아이콘 파비콘 크기 수정
  index.html
  public/assets/images/apple-icon.png
Labels: 📄 docs

#136 [refactor] : 글씨 수정
  src/components/profile/report/graph/Chip.tsx
Labels: 🛠 refactor

#138 [refactor] : 헤더 로고 변경
  src/assets/icons/Logo.svg
  src/components/common/header/Header.Style.ts
  src/components/common/header/Header.tsx
Labels: 🛠 refactor

#140 [feat] : 홈 페이지 반응형 UI 구현
  src/components/common/card/Card.Style.ts
  src/components/common/cardList/CardList.Style.ts
  src/components/common/coinModal/CoinModal.Style.ts
  src/components/common/footer/Footer.Style.ts
  src/components/common/footer/Footer.tsx
  src/components/common/headNews/HeadNews.Style.ts
  src/components/common/pageNation/PageNation.Style.ts
  src/components/common/pageNation/PageNation.tsx
  src/components/common/tag/Tag.Style.ts
  src/components/home/insight/Insight.Style.ts
  src/components/home/insight/Item.Style.ts
  src/components/home/latestNews/LatestNews.Style.tsx
  src/pages/home/Home.Style.ts
Labels: ✨ feature, 💄 ui

#147 [feat] : 헤더 반응형 UI 구현
  src/assets/icons/Etc.svg
  src/components/common/header/Header.Style.ts
  src/components/common/header/Header.tsx
  src/components/common/header/SearchBar.Style.ts
  src/pages/market/Market.Style.ts
  src/pages/profile/Profile.Style.ts
Labels: 💄 ui

#148 [feat] : 마이페이지 반응형 UI 구현
  src/components/common/tag/Tag.Style.ts
  src/components/home/latestNews/LatestNews.Style.ts
  src/components/profile/activities/Activites.Style.ts
  src/components/profile/activities/analysisCard/AnalysisCard.Style.ts
  src/components/profile/activities/insight/Insight.Style.ts
  src/components/profile/activities/insight/Item.Style.ts
  src/components/profile/activities/insight/Item.tsx
  src/components/profile/activities/quiz/Quiz.Style.ts
  src/components/profile/activities/quiz/Quiz.tsx
  src/components/profile/activities/scrap/Scrap.Style.ts
  src/components/profile/calendar/Calendar.Style.ts
  src/components/profile/editProfile/EditProfile.Style.ts
  src/components/profile/keywordModal/KeywordModal.Style.ts
  src/components/profile/profileCard/ProfileCard.Style.ts
  src/components/profile/report/Report.Style.ts
  src/components/profile/report/graph/Graph.Style.ts
  src/components/profile/report/interest/Interest.Style.ts
  src/components/profile/report/keyword/KeywordList.Style.ts
  src/components/profile/report/trend/Item.Style.ts
  src/pages/profile/Profile.Style.ts
Labels: ✨ feature, 💄 ui

#151 [feat] : 검색페이지 반응형 UI 구현
  src/components/common/header/Header.Style.ts
  src/pages/market/Market.Style.ts
  src/pages/profile/Profile.Style.ts
  src/pages/search/Search.Style.ts
Labels: 💄 ui

#154 [feat] : 큰 카테고리 페이지 반응형 UI 구현
  README.md
  src/components/common/card/Card.Style.ts
  src/components/common/headNews/HeadNews.Style.ts
  src/components/common/tabBar/TabBar.Style.ts
  src/pages/category/Category.Style.ts
Labels: ✨ feature, 💄 ui

#155 [feat] : 인트로 페이지 반응형 UI 구현
  src/components/common/header/Header.Style.ts
  src/components/common/header/Header.tsx
  src/components/intro/intro1/Intro_1.Style.ts
  src/components/intro/intro2/Intro_2.Style.ts
  src/components/intro/intro2/Intro_2.tsx
  src/components/intro/kakaoLogin/KakaoLogin.Style.ts
  src/components/intro/layout/CommonLayout.Style.ts
  src/components/intro/layout/IntroContent.Style.ts
Labels: 💄 ui

#145 [feat] : 뉴스 상세 페이지 반응형 UI 구현
  src/components/common/button/PageButton.Style.ts
  src/components/newsDetail/emojipart/EmojiPart.Style.ts
  src/components/newsDetail/emojipart/EmojiPart.tsx
  src/components/newsDetail/quiz/AnswerModal.Style.ts
  src/components/newsDetail/quiz/Quiz.Style.ts
  src/pages/newsDetail/NewsDetail.Style.ts
  src/pages/newsDetail/NewsDetail.tsx
Labels: 💄 ui

#156 [fix] : 중앙 정렬 해결
  src/components/intro/intro2/Intro_2.Style.ts
  src/components/intro/layout/CommonLayout.Style.ts
  src/components/intro/layout/CommonLayout.tsx
Labels: 🛠 refactor, 💄 ui

#158 [feat] : 마켓 페이지 반응형 UI 구현
  src/components/market/ItemList.Style.ts
  src/pages/market/Market.Style.ts
  src/pages/market/Market.tsx
Labels: 💄 ui

#160 [feat] : 푸터 아이템 수정
  src/assets/icons/GitHubIcon.svg
  src/assets/icons/MailIcon.svg
  src/components/common/footer/Footer.Style.ts
  src/components/common/footer/Footer.tsx
Labels: ✨ feature, 💄 ui
